services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./my-app:/app
      - clioguesser_frontend:/app/node_modules
    command: npm run dev -- --host
    container_name: clioguesser-frontend-dev-kit
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    networks:
      - clioguesser-net

volumes:
  clioguesser_frontend:

networks:
  clioguesser-net:
    name: clioguesser-net
    driver: bridge
