services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: clioguesser-frontend-nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    networks:
      - clioguesser-net

volumes:
  clioguesser_frontend:

networks:
  clioguesser-net:
    name: clioguesser-net
    driver: bridge
