services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./my-app:/app
      - /app/node_modules
    command: npm run dev -- --host
    container_name: clioguesser-frontend-dev-kit
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - clioguesser-net

networks:
  clioguesser-net:
    name: clioguesser-net
    driver: bridge
