name: Build and Check Formatting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
        working-directory: svelte-map-app
      - name: Check svelte
        run: npx prettier src/App.svelte > svelte.txt
        working-directory: svelte-map-app
      - name: Do diff
        run: diff svelte.txt src/App.svelte
        working-directory: svelte-map-app
      - name: Check formatting
        run: npx prettier --check ..
        working-directory: svelte-map-app
      - name: Build
        run: npm run build
        working-directory: svelte-map-app
